# Generated by Django 5.2.4 on 2025-07-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('translated_title', models.CharField(blank=True, max_length=200, null=True)),
                ('language', models.CharField(default='en', max_length=10)),
            ],
        ),
    ]
